{
 "title": "EC2",
 "tags": [
  "ec2",
  "aws",
  "cloudwatch",
  "cpu",
  "disk",
  "status"
 ],
 "time": { "from": "now-15m", "to": "now" },
 "templating": {
  "list": [
   { "name": "Region", "query": "regions()" },
   {
    "name": "Instance",
    "query": "dimension_values($Region,AWS/EC2, CPUUtilization, InstanceId)"
   }
  ]
 },
 "panels": [
  {
   "title": "Network Traffic",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    {
     "alias": "{{metric}}",
     "dimensions": { "InstanceId": "$Instance" },
     "metricName": "NetworkIn",
     "namespace": "AWS/EC2",
     "region": "default",
     "statistics": [ "Average" ]
    },
    {
     "alias": "{{metric}}",
     "dimensions": { "InstanceId": "$Instance" },
     "metricName": "NetworkOut",
     "namespace": "AWS/EC2",
     "region": "default",
     "statistics": [ "Average" ]
    }
   ]
  },
  {
   "title": "CPU",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "alias": "{{metric}}",
     "dimensions": { "InstanceId": "$Instance" },
     "metricName": "CPUUtilization",
     "namespace": "AWS/EC2",
     "region": "default",
     "statistics": [ "Average" ]
    }
   ]
  },
  {
   "title": "Disk R/W",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "alias": "{{metric}}",
     "dimensions": { "InstanceId": "$Instance" },
     "metricName": "DiskReadBytes",
     "namespace": "AWS/EC2",
     "region": "default",
     "statistics": [ "Average" ]
    },
    {
     "alias": "{{metric}}",
     "dimensions": { "InstanceId": "$Instance" },
     "metricName": "DiskWriteBytes",
     "namespace": "AWS/EC2",
     "region": "default",
     "statistics": [ "Average" ]
    }
   ]
  },
  {
   "title": "Status",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 12, "x": 12, "y": 9 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "dimensions": { "InstanceId": "$Instance" },
     "metricName": "StatusCheckFailed",
     "namespace": "AWS/EC2",
     "region": "default",
     "statistics": [ "Maximum" ]
    }
   ]
  },
  {
   "title": "CPU Credit Usage",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 12 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "dimensions": { "InstanceId": "$Instance" },
     "metricName": "CPUCreditUsage",
     "namespace": "AWS/EC2",
     "region": "default",
     "statistics": [ "Average" ]
    }
   ]
  },
  {
   "title": "CPU Credit Balance",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 12 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "dimensions": { "InstanceId": "$Instance" },
     "metricName": "CPUCreditBalance",
     "namespace": "AWS/EC2",
     "region": "default",
     "statistics": [ "Average" ]
    }
   ]
  }
 ]
}